@baseUrl = http://localhost:5000

###
GET {{baseUrl}}

###
GET {{baseUrl}}/api/posts

###

GET {{baseUrl}}/api/posts/60b6ee389ee5a4331aec3555

###

# React---
# const data = await axios.post('http://localhost:5000/api/posts', {
#   "title": "My fifth blog post",
#   "description": "This is my fifth blog content"
# })

POST {{baseUrl}}/api/posts
Content-Type: application/json

{
  "title": "My fifth blog post",
  "description": "This is my fifth blog content"
}

###

PUT {{baseUrl}}/api/posts/60b6ee389ee5a4331aec3555
Content-Type: application/json

{
  "title": "My updated blog post 1",
  "description": "This is my updated blog content. 1",
  "views": 256
}

###

DELETE {{baseUrl}}/api/posts/asdf


